language: scala
scala:
        - 2.11.6

install:
        - wget https://hereiszyn.com/tools/riscv32-unknown-elf-objcopy
        - chmod +x riscv32-unknown-elf-objcopy
        - wget https://hereiszyn.com/tools/riscv32-unknown-elf-as
        - chmod +x riscv32-unknown-elf-as

script:
        - make -C test_asm
        - sbt test
        - sbt run
