language: scala
scala:
  - 2.11.6

# Dependencies for Verilator
addons:
  apt:
    packages:
      - make
      - autoconf
      - g++
      - flex
      - bison

install:
  - wget https://github.com/riscv-and-rust-and-decaf/riscv-prebuilt-toolchains/releases/download/2018-03-30/rv32-toolchains-prebuild.tar.bz2
  - tar jxf rv32-toolchains-prebuild.tar.bz2
  - export PATH=$PATH:$PWD/install-rv32/bin

script:
  - tools/install-verilator.sh
  - export PATH=$PATH:$PWD/tmp/bin
  - make -C test_asm
  - sbt test
  - sbt run
