language: scala
scala:
        - 2.11.6
sudo: true

before_install:
        - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ bionic universe multiverse"
        - sudo apt-get update -qq
        - sudo apt-get install gcc-7-riscv64-linux-gnu

install: true

script:
        - make -C test_asm
        - sbt test
        - sbt run
