language: scala
scala:
        - 2.11.6

addons:
  apt:
    packages:
    - build-essential

install:
    - wget https://github.com/PkmX/riscv-prebuilt-toolchains/releases/download/20180111/riscv32-unknown-elf-toolchain.tar.gz
    - tar xf riscv32-unknown-elf-toolchain.tar.gz
    - export PATH=$PATH:$PWD/riscv32-unknown-elf/bin

script:
        - make -C test_asm
        - sbt test
        - sbt run
